###
# Create Member
POST http://localhost:9090/v1/members
Accept: application/json
Content-Type: application/json
API-KEY: SECRET

{
  "email": "member1@gmail.com",
  "phone": "0899999999",
  "name": "Joko Moro"
}

###
# Update Member
PUT http://localhost:9090/v1/members/6d208f26-679d-4cf4-b322-3b81d55ca8c4
Accept: application/json
Content-Type: application/json
API-KEY: SECRET

{
  "name": "Joko Heru",
  "verified": true
}

###
# Get Member
GET http://localhost:9090/v1/members/bc50306a-3b28-45e4-bdd3-cbd69b07126a
Accept: application/json
API-KEY: SECRET

###

# TopUp Transaction
POST http://localhost:9090/v1/transactions/topup
Accept: application/json
Content-Type: application/json
API-KEY: SECRET

{
  "memberId": "bc50306a-3b28-45e4-bdd3-cbd69b07126a",
  "total": 1000000
}

###

# Point Transaction
POST http://localhost:9090/v1/transactions/point
Accept: application/json
Content-Type: application/json
API-KEY: SECRET

{
  "memberId": "bc50306a-3b28-45e4-bdd3-cbd69b07126a",
  "total": 5000000
}

###

# Purchase Transaction
POST http://localhost:9090/v1/transactions/purchase
Accept: application/json
Content-Type: application/json
API-KEY: SECRET

{
  "memberId": "bc50306a-3b28-45e4-bdd3-cbd69b07126a",
  "total": 100000
}

###

# Transfer Transaction
POST http://localhost:9090/v1/transactions/transfer
Accept: application/json
Content-Type: application/json
API-KEY: SECRET

{
  "memberId": "bc50306a-3b28-45e4-bdd3-cbd69b07126a",
  "total": 1000000,
  "bank": "BCA",
  "bankAccountNumber": "024124124"
}

###

# List Transactions
GET http://localhost:9090/v1/transactions/bc50306a-3b28-45e4-bdd3-cbd69b07126a
Accept: application/json
API-KEY: SECRET

###

# List Transfer
GET http://localhost:9090/v1/transfers/bc50306a-3b28-45e4-bdd3-cbd69b07126a
Accept: application/json
API-KEY: SECRET

###